furryshit = ["Rawr x3",
    "nuzzles",
    "how are you",
    "pounces on you",
    "you're so warm o3o",
    "notices you have a bulge o:",
    "someone's happy :wink:",
    "nuzzles your necky wecky~ murr~",
    "hehehe rubbies your bulgy wolgy",
    "you're so big :oooo ",
    "rubbies more on your bulgy wolgy",
    "it doesn't stop growing ·///·",
    "kisses you and lickies your necky",
    "daddy likies (;",
    "nuzzles wuzzles I hope daddy really likes $:",
    "wiggles butt and squirms",
    "I want to see your big daddy meat~",
    "wiggles butt I have a little itch o3o",
    "wags tail can you please get my itch~",
    "puts paws on your chest nyea~",
    "its a seven inch itch",
    "rubs your chest can you help me pwease",
    "squirms pwetty pwease sad face",
    "I need to be punished runs paws down your chest and bites lip",
    "like I need to be punished really good~",
    "paws on your bulge as I lick my lips I'm getting thirsty.",
    "I can go for some milk",
    "unbuttons your pants as my eyes glow",
    "you smell so musky :v",
    "licks shaft mmmm~"]

facts = ["Fun fact, pandas are so fucking stupid that they roll over onto their babies and fucking kill them, they kill their own fucking babies. Fucking stupid, fucking impish brained animals. There is no point in their existence just become extinct already, fuck off.",
"Now, according to world population studies there has been approximately 108 BILLION people on this planet so far. The average lifespan for people is 0-25 years. If we multiply the average lifespan (25) by the 108 billion people, there has been 2.7 TRILLION years of life. If we multiply that by how many days are within a year (365) there has been approximately 985 TRILLION years of life. And not ONCE, in any of those days, did anybody ask.",
"Fun fact, people who are able to perform self-fellatio report that it feels more like sucking a dick, rather than getting your dick sucked. Why?\n\nThe reason is simple: neurological latency. The nerves for your mouth are closer to your brain than the nerves of your cock. So your body feels the sensation from the mouth before the sensations of the cock. The mouth sensations over-shadow the pleasurable sensations, which is why those who self-fellate feel like they’re sucking a dick, rather than getting their dick sucked.",
"A group of ravens is called a murder.",
"Bus seats are designed so that you cannot tell how dirty they really are.",
"Your intestines will “wriggle” themselves back into the correct position.\nDoctors who do any type of intestinal surgery don’t have to worry (too much) about how they put the intestines back in.",
"A certain type of angler fish reproduce via the male burrowing into the side of the female, eventually fusing. The males life is lost in the process.",
"When you get a sunburn, it's actually your cells dying so they don't get tumorous.",
"Horses can't throw up.\nSo if they eat something bad or get a bad gas bubble, they just lay down and die.",
"In the United States roughly 1/3 of all food is thrown away each year.",
"There are 8 unaccounted for American nukes and literally an unknown quantity of missing soviet nukes that range all the way from warheads to suitcase bombs.",
"The lemmings are not suicidal and the documentary that filmed it was actually showing lemmings getting thrown down a cliff because they needed the scene but couldn't make the animals do it."
"Live Chat support agents can see what you type before you send it, so they can reply quicker.",
"You can smell your own lungs. Your brain just filters out the smell.",
"In Australia there is a plant called the Gympie-Gympie which has such a severe sting that horses who brush against it throw themselves off cliffs because they’d rather die than continue to experience the pain.",
"If a hamster gets too stressed, it will eats its kids.",
"According to the World Bank Group, the world produces about 2 billion tons of garbage every year.",
"There is a non-zero maximum threshold for the amount of cockroach that can be present in ground coffee because it is literally impossible to keep them out entirely.",
"The threat of a deadly bird flu spreading to humans is always there. It takes just a little bit of negligence in screening chickens for this to happen.",
"The reason dogs love squeaky toys is because they sound like small animals dying.",
"There is a whale called 52 Blue that only sings at their frequency meaning it can't communicate with other whales. It is nicknamed the loneliest whale on the planet.",
"The FBI estimates there are between 25-50 active serial killers in the US at any given time.",
"No one went to prison over the Panama Papers.",
"Sometimes you're the bad guy.",
"If 2 male flat worms meet, they will sword fight with their dicks until one loses. The loser will become female and they will mate.",
"There's something called a gamma ray burst, basically some stars will periodically produce a burst of gamma rays with no warning. If this happens to a star close enough to the earth and hits the earth(not all that unlikely, they spread out quite a bit while still being deadly) we'll be hit by a burst of gamma radiation with no warning. Every living thing on the side of the earth it hits will die and earth's atmosphere will be permanently damaged, this could lead to most of not all of the population of the other side of the planet also dying.\n\nIt's a civilisation ending event and there's nothing we can do to defend against or predict it."]